# Site settings
title: Maxwell Bernstein
email: max@bernsteinbear.com
baseurl: ""
url: "http://bernsteinbear.com"

permalink: '/blog/:title'
post_dirs: false

# Build settings
markdown: kramdown

gems:
  - jekyll-feed
