# Site settings
title: Maxwell Bernstein
email: max@bernsteinbear.com
description: Programmer, photographer, and xyz.
baseurl: ""
url: "http://bernsteinbear.com"
twitter_username: tekknolagi
github_username: tekknolagi
photos_link: http://photos.bernsteinbear.com

project_img_path: /assets/img/projects/
relative_permalinks: true

# Build settings
markdown: kramdown
