# Site settings
title: Maxwell Bernstein
author: Maxwell Bernstein
author_nickname: Max Bernstein
email: max@bernsteinbear.com
baseurl: ""
url: "http://bernsteinbear.com"

twitter:
  username: tekknolagi

permalink: '/blog/:title'
post_dirs: false

# Build settings
markdown: kramdown
kramdown:
  input: GFM # GitHub Flavored Markdown
  hard_wrap: false
highlighter: rouge

gems:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
