# Site settings
title: Max Bernstein
author: Max Bernstein
author_nickname: Max Bernstein
email: max@bernsteinbear.com
description: "Max Bernstein's personal website and blog"
baseurl: ""
url: "http://bernsteinbear.com"

twitter:
  username: tekknolagi

permalink: '/blog/:title'
post_dirs: false

# Build settings
markdown: kramdown
kramdown:
  input: GFM # GitHub Flavored Markdown
  hard_wrap: false
highlighter: rouge

gems:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - rouge

collections:
    blog_lisp:
        output: true
        permalink: /blog/lisp/:path/

defaults:
    - scope:
        collection: blog_lisp
      values:
        layout: post
