# Site settings
title: Max Bernstein
# Site's name
name: Max Bernstein's Blog
author: Max Bernstein
author_nickname: Max Bernstein
email: max@bernsteinbear.com
description: ""
baseurl: ""
url: "https://bernsteinbear.com"
exclude: [vendor]
include: [.well-known]

future: false

twitter:
  username: tekknolagi

repo:
  repository_url: https://github.com/tekknolagi/tekknolagi.github.com
  branch: master

permalink: '/blog/:title/'
post_dirs: false

# Build settings
markdown: kramdown
kramdown:
  input: GFM # GitHub Flavored Markdown
  hard_wrap: false
highlighter: rouge

gems:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - rouge

collections:
    blog_lisp:
        output: true
        permalink: /blog/lisp/:path/
    recipes:
        output: true
        permalink: /recipes/:path/

default_og_image: "/favicon.ico"
